### ISSUE TITLE
Find the malware binaries to identify what botnet I catched

### ISSUE THREAD

**Issue by schroe-ja** [honeynet/riotpot#54]
Is there a way to get the malware binaries from the high-interaction services? 

Do I have to start the high-interaction services somewhere in the `riotpot` Dockerfile?

**Comment by RicYaben** [comment]
Not at this point :) implementing this feature should be trivial though. I will keep this open to see if somebody wants to give it a go

**Comment by schroe-ja** [comment]
So it's only possible to use the `pcap` files for creating a dataset?
I mean I have to make a malware analysis based on the traffic to identify the botnets

**Comment by RicYaben** [comment]
You have a very specific and complicated case in mind that requires quite a large field of knowledge. I think you may be better off using [T-Pot](https://github.com/telekom-security/tpotce) though, but keep in mind that what you are looking for requires a well-defined scope, e.g., protocols, services, and kind of attacks you are trying to capture. 

If you are only interested in analyzing malware traces, why not use Virustotal? otherwise, you will need to be clear on the kind of services you are exposing and have some idea of how these botnets drop their malware (e.g., SSH + wget, inside some payload request, FTP upload, MQTT topics, etc.).

I recommend taking a look at the literature on botnet identification, or some online tutorials that give you a walkthrough on how to set up a honeypot for your use-case.

**Comment by schroe-ja** [comment]
Ok, I understand what you mean. 
So I can use RIoTPot to capture malicious traffic and analyze it via i.e. Arkime? And then using my analysis results for improving IDS rules or something else.

**Comment by RicYaben** [comment]
Yes :) but I still recommend T-Pot for your specific case. That honeypot comes with everything you will need and is more stable. Right now we are making some modifications to RIoTPot and it is not stable. I hope this helps!

**Comment by schroe-ja** [comment]
Ok thanks. I looked and tried T-Pot which is very heavy and I have already written a shell script to configure all my VMs for riotpot ^^.
My PhD is about identification of IoT Botnets which is why I chose riotpot.
